services:
  pdi-carte:
    build:
      context: .
      dockerfile: Dockerfile
    image: pentaho-install
    environment:
      - TZ=Pacific/Tahiti
      - PENTAHO_DI_JAVA_OPTIONS=-Xms512m -Xmx2g -Dfile.encoding=UTF-8
      - PDI_MODE=carte
      - CARTE_HOST=0.0.0.0
      - CARTE_PORT=8080
      - CARTE_USER=admin
      - CARTE_PASS=changeit
      - KETTLE_LEVEL=Basic
    ports:
      - "8080:8080"
    # montage volume pour jobs Pentaho
    volumes:
      - pentaho_jobs:/jobs:ro
      - pentaho_workdir:/workdir:rw     
    restart: unless-stopped 

# volume externe défini en top-level
volumes:
  pentaho_jobs:
    external: true
  pentaho_workdir:
    external: true

