version: "3.9"

services:
  pdi-jobs:
    build:
      context: .
      dockerfile: Dockerfile
    image: pentaho-exec
    working_dir: /opt/pdi
    environment:
      - TZ=Pacific/Tahiti
      - PENTAHO_DI_JAVA_OPTIONS=-Xms512m -Xmx2g -Dfile.encoding=UTF-8
    # kitchen en entrypoint, affiche version et sort
    entrypoint: ["/opt/pdi/kitchen.sh"]
    command: ["-version"]
    # montage volume pour jobs Pentaho
    volumes:
      - pentaho_jobs:/jobs:ro

# volume externe défini en top-level
volumes:
  pentaho_jobs:
    external: true