[project]
name = "fastapi_test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.100,<1.0",
    "flask>=3.1.0",
    "requests>=2.32.3",
    "uvicorn[standard]>=0.34.2",
]
